// vue-app/src/components/Counter.vue
  <script setup>
    import { ref } from 'vue';
    
    const count = ref(0);
    
    const increment = () => count.value++;
    const decrement = () => count.value--;
    const reset = () => count.value = 0;
  </script>

<template>
  <h1>Contador: {{ count }}</h1>
  <div style="text-align: center; padding: 20px; display: flex; justify-content: center; gap: 1rem;">
    <button @click="decrement">-</button>
    <button @click="increment">+</button>
    <button @click="reset">Resetear</button>
  </div>
</template>

// react-app/src/components/Counter.jsx
import { useState } from 'react';

export const Counter = () => {
  const [count, setCount] = useState(0);

  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);
  const reset = () => setCount(0);

  return (
    <>
      <h1>Contador: {count}</h1>
      <div style={{ textAlign: 'center', padding: '20px', display: "flex", gap: "1rem" }}>
        <button onClick={decrement}>-</button>
        <button onClick={increment}>+</button>
        <button onClick={reset}>Resetear</button>
      </div>
    </>
  );
}
